### ISSUE TITLE
회의록 2021.10.14

### ISSUE THREAD

**Issue by qpdh** [3DArtAuction/3DArtAuction_Doc#4]
# 3D Art Auction

# 기능 정리
# 1. 공통
## 1. Login
1. 판매자 로그인
    1. 판매만 가능(구매 불가)
2. 구매자 로그인
    1. 구매만 가능(판매 불가)
    2. 찜목록, 구매기록

## 2. Viewer
1. 2D
1. Photo Viewer
    1. 그림
2. 3D

## 3. 경매
1. 시작가, 추정가
2. 가격 간격 설정
1. 1000 -> 1001 (X)  
        1000 -> 1100 (O)
3. 시작시간, 종료시간

## 4. 카테고리
1. 조각상
2. 그림

## 5. 검색
1. 작가
2. 태그
3. 제목

## 6. 예술품 정렬
1. 가격별 정렬
2. 인기순 정렬
3. ...

## 7. 작품 추천 (내가 구매했던 예술품 기준?)
1. % 일치?
- 동일 태그를 이용한 구현
    - 현재 작품의 태그와 B의 태그를 비교해서 얼마나 일치하는지?  
        -> 작품당 점수 매기기  
        -> 작품이 DB에 100개가 있지만, 전부를 보여줄 수 없음   
        -> 상위 5개를 보여주자  
    - 현재 A작품을 보는데, B작품이 추천 대상이다
    - 옷을 사는 앱 (유저의 추천 정보) (홈 화면) 상품 클릭  
        -> A 상품과 연관 있는 것을 추천
    
    - 같은 작가의 작품
        

## 8. 작품의 개수
- 단일

## 9. 커뮤니티
1. 팔로우 기능 (작가 팔로우)
2. 작가의 게시글
1. 유튜브 커뮤니티 참고
2. 언제 작품이 나온다.. 등등
3. 작가 프로필
1. 프로필 사진
2. 작가 소개
3. 작가의 작품

## 10. 택배 조회 기능
1. [운송장 번호를 입력하면 정보를 출력](https://github.com/papav-hub/Present_Recommendation_app)
2. [Delivery Tracker - 배송 조회 API 서비스](https://tracker.delivery/guide/)

# 2. 웹(Web)
## 1. 상품 등록(전용 기능)
1. 경매정보
2. 사진(2D or 3D)
3. 작품 설명
4. 재질
1. 캔버스
2. 유채
## 2. 

# 3. 앱(Android IOS)
## TODO
3D 모델링은 보류, 웹에서 3D 모델링 구현 우선

## 1. 알람 Android Notification
- 앱이 꺼져도 알람이 갈 수 있는 기능
- 백그라운드에서 알람이 갈 수 있는 기능
1. 내가 팔로우한 작가의 정보
2. 판매 종료 시간 기준으로 알람
3. 낙찰 됐는지

# DB 설계
## 1. Table
1. Artist
   1. Artist_NO (integer) **Primary Key**
   2. Artist_ID (integer)
   3. Artist_PW (varchar 20) 작가 비밀번호
   4. Artist_Name (varchar 20) 작가 이름
   5. Artist_Profile (varchar 20) url
   6. Artist_Information (varchar 50) 작가 설명
   7. Artist_Register_Date (date) 가입 날짜
   8. Artist_Level (integer)
      - 상한선에서 몇% 올랐는지
      - == 1 : 아마추어 (**기본값**)
      - == 2 : 프로

2. Customer
   1. Customer_NO (integer) **Primary Key**
   2. Customer_ID (integer)
   3. Customer_PW (varchar 20) 사용자 비밀번호
   4. Customer_Name (varchar 20) 사용자 이름
   5. Customer_Profile (varchar 20) url
   6. Customer_Register_Date (date) 가입 날짜
   7. Customer_Address (varchar 20) 배송지
   8. Customer_Phone_Number (varchar 20) 전화번호
   9. Customer_Point (integer)

3. Piece
   1. Piece_NO (integer) **Primary Key**
   2. Artist_NO **Foreign Key**
   3. Piece_Title (varchar 20) 작품 제목
   4. Category_ID (integer) 작품 카테고리
   5. Piece_Information (varchar 50) 작품 설명
   6. Piece_Lower_Limit (integer) 하한선
   7. Piece_Bid_Increment (integer) 호가 단위
   8. Piece_2d_image (varchar 20) url 
   9.  Piece_3d_image (varchar 20) url
   10. Piece_Source
   11. Piece_X (double) 가로
   12. Piece_Y (double) 세로
   13. Piece_Z (double) 높이
   14. Piece_Birthday (date) 제작 일자
   15. Piece_Upload_Date (date) 게시글 업로드 일자

4. Category
   1. Category_ID (integer) **Primary Key**
   2. Category_Name (varchar 20) 

5. Purchase_History
   1. Piece_NO (integer) **Primary Key**
   2. Customer_ID (integer) **Foreign Key**
   3. Purchase_Time (date) 

6. Tag
   1. Tag_ID (integer) **Primary Key**
   2. Tag_Name (varchar 20) 

7. Tag-Piece
   1. Tag_ID (integer) **Primary Key**
   2. Piece_ID (integer) **Primary Key**

# 개발 일정
## ~21.12.31 완료 목적

# 월간
## 1. 10월
1. 설계 완료
   
## 2. 11월
1. 개발
   
## 3. 12월
1. 개발
2. 테스트 (1주일)
3. 12.31 마무리

# 주간
1. 설계 완료

# 다음 미팅 날짜

**Comment by papav-hub** [comment]
추가 기능 (Size 비교)

**Comment by papav-hub** [comment]
작가의 참고자료 (link)
![image](https://user-images.githubusercontent.com/67986703/137459900-d97c17f4-04e8-495c-beac-de86a51c6378.png)

**Comment by papav-hub** [comment]
3D file 한장만 가능

**Comment by papav-hub** [comment]
서버 주기마다 돌려서 배송완료 확인해줘야됨

**Comment by papav-hub** [comment]
DB 작가 전화번호

**Comment by papav-hub** [comment]
- 예치금
- 경매 참여하면 예치금
